version: '3.4'
services:
    load-balancer:
      image: nginx:latest
      container_name: load-balancer
      volumes:
         - ./load-balancer-nginx.conf:/etc/nginx/nginx.conf:ro
         - ./ssl:/etc/nginx/ssl:ro
      restart: always
      depends_on:
         - nginx_node1
         - nginx_node2
      ports:
         - '80:80'
         - '443:443'
      networks:
         - backend
      healthcheck:
           test: ["CMD", "service", "nginx", "status"] 
           interval: 1m
           timeout: 10s
           retries: 3
           start_period: 40s
      logging:
           driver: journald
           options:
              tag: load-balancer

    nginx_node1:
      image: nginx:latest
      container_name: nginx_node1
      volumes: 
         - ./site:/var/www/html
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
         - ./htpasswd:/etc/nginx/conf/htpasswd:ro
         #- ./ssl:/etc/nginx/ssl:ro  
      restart: always     
      expose:
         - '80'
         - '443'
      networks:
         - backend  
      healthcheck:
           test: ["CMD", "service", "nginx", "status"]
           interval: 1m
           timeout: 10s
           retries: 3
           start_period: 40s
      logging:
           driver: journald
           options:
              tag: nginx_node1
                                                          
    nginx_node2:
      image: nginx:latest
      container_name: nginx_node2
      volumes:
         - ./site:/var/www/html
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
         - ./htpasswd:/etc/nginx/conf/htpasswd:ro
         #- ./ssl:/etc/nginx/ssl:ro
      restart: always
      expose:
         - '80'
         - '443'
      networks:
         - backend
      healthcheck:
           test: ["CMD", "service", "nginx", "status"]
           interval: 1m
           timeout: 10s
           retries: 3
           start_period: 40s
      logging:
           driver: journald
           options:
              tag: nginx_node2

networks:
  backend:
    driver: bridge
