VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "devops-test"
  config.vm.box_url = [
     "file://./devops-test.box"
  ]
  
  config.vm.network :forwarded_port, guest: 80, host: 8080    # Apache HTTP
  config.vm.network :forwarded_port, guest: 443, host: 8443   # Apache HTTPS
  config.vm.network :forwarded_port, guest: 5000, host: 5000  # Flask debug server
  
  config.vm.provision "file", source: "files/site.conf", destination: "/tmp/site.conf"
  config.vm.provision "file", source: "files/app.py", destination: "/tmp/app.py"
  config.vm.provision "file", source: "files/vagrant_cron", destination: "/tmp/vagrant_cron"
  config.vm.provision "shell", path: "files/provision.sh"
  
end
