apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    server {
        listen 80;
        location /nginx-blackout {
            root /usr/share/nginx/html;
            index blackout.html;
        }
        location / {
            if ($time_iso8601 ~ ^2020-03-13T23:2[0-9]:[0-9][0-9]) {
                return 301 /nginx-blackout;
            }
            root /usr/share/nginx/html;
            index index.html;
        }
    }


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: intelligent12/hw1
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/
      volumes:
          - name: nginx-config
            configMap:
              name: nginx-configmap

---

kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: my-nginx
  ports:
    - port: 80
      targetPort: 8080

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: nginx-service
            servicePort: 8080
