VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "neve/devops-test"
  config.vm.box_url = [
     "file://./devops-test.box"
  ]
  
  config.vm.network :forwarded_port, guest: 80, host: 8080    # Apache HTTP
  config.vm.network :forwarded_port, guest: 443, host: 8443   # Apache HTTPS
  config.vm.network :forwarded_port, guest: 5000, host: 5000  # Flask debug server
  
  config.vm.provision "file", source: "files/site.conf", destination: "/tmp/site.conf"
  config.vm.provision "shell", path: "files/provision.sh"
  config.vm.provision "shell", path: "files/cron.sh"
  
  # config.vm.synced_folder "#{ENV['HOME']}/devops-test-share", "/var/www/devops-test-share"
  
end
