#!/bin/bash
TEST=$(cat /etc/resolv.conf | grep arya.ns.cloudflare.com) 
if [ -z TEST ]
  then echo "arya.ns.cloudflare.com" >> /etc/resolv.conf
  else echo "arya already added"
fi
TEST=$(cat /etc/resolv.conf | grep chance.ns.cloudflare.com)
if [ -z TEST ]
  then echo "chance.ns.cloudflare.com" >> /etc/resolv.conf
  else echo "chance already added"
fi
