VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "qwe765/test"

  config.vm.network :forwarded_port, guest: 80, host: 8080    # Apache HTTP
  config.vm.network :forwarded_port, guest: 443, host: 8443   # Apache HTTPS
  config.vm.network :forwarded_port, guest: 5000, host: 5000  # Flask debug server

end
