VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "neve/devops-test"
  config.vm.box_url = [
     "file://./devops-test.box"
  ]
  
  config.vm.network :forwarded_port, guest: 80, host: 8080    # Apache HTTP
  config.vm.network :forwarded_port, guest: 443, host: 8443   # Apache HTTPS
  
  config.vm.provision "file", source: "files/configs/site.conf", destination: "/tmp/site.conf"
  config.vm.provision 'file', source: 'files/app', destination: '/tmp/app'
  config.vm.provision "shell", path: "files/scripts/generate-ssl.sh"
  config.vm.provision "shell", path: "files/scripts/provision.sh"
  config.vm.provision "shell", path: "files/scripts/run_cron.sh"

end
