
Vagrant.configure("2") do |config|
 
  config.vm.box = "devops-test"
   config.vm.box_url = [
     "file://./devops-test.box"
  ]
  
  config.vm.network :forwarded_port, guest: 80, host: 8080, host_ip: "127.0.0.1"    # Apache HTTP
  config.vm.network :forwarded_port, guest: 443, host: 8443   # Apache HTTPS
  config.vm.network :forwarded_port, guest: 5000, host: 5000  # Flask debug server
  
  config.vm.provision "file", source: "files/site.conf", destination: "/tmp/site.conf"
config.vm.provision "shell", path: "files/provision.sh"
 

end
